on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            -   name: Checkout
                run: |
                ls -a
                echo ${{GITHUB_REPOSITORY}}
                