on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            -   name: Checkout
                run: echo "GITHUB REPOSITORY) ${GITHUB_REPOSITORY}""
                
